SELECT
    NAME + '(' + SUBSTRING(OCCUPATION, 1, 1 ) + ')'
FROM
    OCCUPATIONS
ORDER BY
    NAME;

SELECT
    'There are a total of ' + CAST(COUNT(NAME) AS VARCHAR) + ' ' + LOWER(OCCUPATION) + 's.'
FROM
    OCCUPATIONS
GROUP BY
    OCCUPATION
ORDER BY
    COUNT(NAME),
    OCCUPATION;