SELECT
    C.COMPANY_CODE,
    C.FOUNDER,
    COUNT(distinct E.LEAD_MANAGER_CODE),
    COUNT(distinct E.SENIOR_MANAGER_CODE),
    COUNT(distinct E.MANAGER_CODE),
    COUNT(distinct E.EMPLOYEE_CODE)
FROM
    COMPANY  C
    JOIN EMPLOYEE E
    on C.COMPANY_CODE = E.COMPANY_CODE
GROUP BY
    C.COMPANY_CODE,
    C.FOUNDER
ORDER BY
    C.COMPANY_CODE ASC;